chocolatecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('chocolates/', views.chocolates_index, name="index"),
  path('chocolates/<int:chocolate_id>', views.chocolate_detail, name="detail"),
  path('chocolates/create/', views.ChocolateCreate.as_view(), name='chocolates_create'),
  path('chocolates/<int:pk>/update/', views.ChocolateUpdate.as_view(), name='chocolates_update'),
  path('chocolates/<int:pk>/delete/', views.ChocolateDelete.as_view(), name='chocolates_delete'),
  path('chocolates/<int:chocolate_id>/add_order/', views.add_order, name='add_order'),
  path('chocolates/<int:chocolate_id>/assoc_store/<int:store_id>/', views.assoc_store, name='assoc_store'),
  path('chocolates/<int:chocolate_id>/unassoc_store/<int:store_id>/', views.unassoc_store, name='unassoc_store'),
  path('stores/', views.StoreList.as_view(), name='stores_index'),
  path('stores/<int:pk>/', views.StoreDetail.as_view(), name='stores_detail'),
  path('stores/create/', views.StoreCreate.as_view(), name='stores_create'),
  path('stores/<int:pk>/update/', views.StoreUpdate.as_view(), name='stores_update'),
  path('stores/<int:pk>/delete/', views.StoreDelete.as_view(), name='stores_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

# Create your models here.
chocolates = [
  {'name': 'Melt-Aways', 'type': 'Whipped', 'description': 'A delectable confectionery piece so smooth and so perfect it melts in your mouth', 'flavor': "Milk Chocolate"},
  {'name': 'Butter Cream', 'type': 'Cream Filled', 'description': 'A delicious confectionery piece with a familiar creamy center', 'flavor': "Dark Chocolate"},
]

class Store(models.Model):
  name = models.CharField(max_length=50)
  distance = models.CharField(max_length=5)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('stores_detail', kwargs={'pk': self.id})

class Chocolate(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    flavor = models.CharField(max_length=100)
    stores = models.ManyToManyField(Store)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'chocolate_id': self.id})


class Order(models.Model):
  date = models.DateField('Order Date')
  location = models.CharField(
    max_length=100,
    default="Boston"
  )
  # Create a cat_id FK
  chocolate = models.ForeignKey(
    Chocolate,
    on_delete=models.CASCADE
  )

#   def __str__(self):
#     return f"{self.get_location_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Order

class OrderForm(ModelForm):
  class Meta:
    model = Order
    fields = ['date', 'location']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Chocolate, Store
from .forms import OrderForm


# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def chocolates_index(request):
  # We pass data to a template very much like we did in Express!
  chocolates = Chocolate.objects.all()
  return render(request, 'chocolates/index.html', {
    'chocolates': chocolates
  })

def chocolate_detail(request, chocolate_id):
    chocolate = Chocolate.objects.get(id=chocolate_id)
    order_form = OrderForm()
    id_list = chocolate.stores.all().values_list('id')
    not_at_stores = Store.objects.exclude(id__in=id_list)
    return render(request, 'chocolates/detail.html', {
        'chocolate': chocolate, "order_form": order_form, "stores": not_at_stores
    })

def add_order(request, chocolate_id):
  # create a ModelForm instance using 
  # the data that was submitted in the form
  form = OrderForm(request.POST)
  # validate the form
  if form.is_valid():
    # We want a model instance, but
    # we can't save to the db yet
    # because we have not assigned the
    # cat_id FK.
    new_order = form.save(commit=False)
    new_order.chocolate_id = chocolate_id
    new_order.save()
  return redirect('detail', chocolate_id=chocolate_id)


class ChocolateCreate(CreateView):
  model = Chocolate
  fields = '__all__'

class ChocolateUpdate(UpdateView):
  model = Chocolate
  fields = ['type', 'description', 'flavor']

class ChocolateDelete(DeleteView):
  model = Chocolate
  success_url = '/chocolates'

class StoreList(ListView):
  model = Store

class StoreDetail(DetailView):
  model = Store

class StoreCreate(CreateView):
  model = Store
  fields = '__all__'

class StoreUpdate(UpdateView):
  model = Store
  fields = ['name', 'distance']

class StoreDelete(DeleteView):
  model = Store
  success_url = '/stores'

def assoc_store(request, chocolate_id, store_id):
  Chocolate.objects.get(id=chocolate_id).stores.add(store_id)
  return redirect('detail', chocolate_id=chocolate_id)

def unassoc_store(request, chocolate_id, store_id):
  Chocolate.objects.get(id=chocolate_id).stores.remove(store_id)
  return redirect('detail', chocolate_id=chocolate_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
  <h1>About the Chocolates Collector</h1>
  <hr />
  <p>Hire the Chocolates Collector!</p>
  <footer>All Rights Reserved, &copy; 2022 Chocolates Collector</footer>  
{% endblock %}

main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Chocolate Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Chocolates Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'stores_create' %}">Add a Store</a></li>
          <li><a href="{% url 'stores_index' %}">View All Stores</a></li>
          <li><a href="{% url 'chocolates_create' %}">Add a Chocolate</a></li>
          <li><a href="{% url 'index' %}">View All Chocolates</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Chocolates Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/chocolates/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Chocolate Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ chocolate.name }}</span>
    <p>Type: {{ chocolate.type }}</p>
    <p>Description: {{ chocolate.description|linebreaks }}</p>
    <p>Flavor: {{ chocolate.flavor }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'chocolates_update' chocolate.id %}">Edit</a>
    <a href="{% url 'chocolates_delete' chocolate.id %}">Delete</a>
  </div>
</div>
 <!-- New Markup Below -->
 <div class="col s6">
    <form action="{% url 'add_order' chocolate.id %}" method="POST">
      {% csrf_token %}
      <!-- Render the inputs -->
      {{ order_form.as_p }}
      <input type="submit" class="btn" value="Add Order">
    </form>
    <br>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Location</th></tr>
      </thead>
      <tbody>
        {% for order in chocolate.order_set.all %}
          <tr>
            <td>{{order.date}}</td>
            <td>{{order.location}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ chocolate.name }}'s Stores</h3>
    {% if chocolate.stores.count %}
      {% for store in chocolate.stores.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
                {{ store.name }} is {{ store.distance }} Mi. away
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_store' chocolate.id store.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>Not available near you</h5>
    {% endif %}
  </div>
  <!-- Available stores will come after this line -->
  <div class="col s6">
    <h3>Available Stores</h3>
    {% if stores.count %}
      {% for store in stores.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
                {{ store.name }} is {{ store.distance }} Mi. away
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_store' chocolate.id store.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}  
    {% else %}
      <h5>{{chocolate.name}} Already is at all available stores near you</h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/chocolates/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Chocolates List</h1>

{% for choco in chocolates %}
<a href="{% url 'detail' choco.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ choco.name }}</span>
      <p>Type: {{ choco.type }}</p>
      <p>Description: {{ choco.description }}</p>
      <p>Flavor: {{ choco.flavor }}</p>
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Home</h1>
{% endblock %}

main_app/templates/main_app/chocolate_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Chocolate</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' chocolate.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/chocolate_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add Chocolate</h1>
{% endif %}


<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/store_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Store</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'stores_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ store.name }}</span>
        <p>Distance: {{ store.distance }} Mi.</p>
      </div>
      <div class="card-action">
        <a href="{% url 'stores_update' store.id %}">Edit</a>
        <a href="{% url 'stores_delete' store.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/store_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Store</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/store_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Store List</h1>

{% for store in store_list %}
  <a href="{% url 'stores_detail' store.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ store.name }}</span>
            <p>Distance: {{ store.distance }} Mi.</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}